package org.teamthree.telegram;

enum Buttons {
    BUTTON_INFO,
    BUTTON_SETTINGS,
    BUTTON_CURRENCY_REFACTOR,
    BUTTON_BANK_CHOOSER,
    BUTTON_CURRENCY_CHECKER,

    BUTTON_TWO_CURRENCY, BUTTON_THREE_CURRENCY, BUTTON_FOUR_CURRENCY,

    BUTTON_PRIVAT_BANK, BUTTON_MONO_BANK, BUTTON_NBU_BANK,

    BUTTON_USD, BUTTON_EUR, BUTTON_GBP

}