package org.teamthree.telegram;

enum Buttons {
    BUTTON_INFO,
    BUTTON_SETTINGS,
    BUTTON_CURRENCY_REFACTOR,
    BUTTON_BANK_CHOOSER,
    BUTTON_CURRENCY_CHECKER,
    BUTTON_ALERT_TIME,

    BUTTON_TWO_CURRENCY,
    BUTTON_THREE_CURRENCY,
    BUTTON_FOUR_CURRENCY
}